### ISSUE TITLE
도메인 Rule 결정 회의

### ISSUE THREAD

**Issue by zcx6263** [kookmin-sw/2018-cap1-4#1]
Expert System 도메인 Rule 결정에 대해서 회의가 필요합니다.

기존 인턴에서 사용하던 Rule을 토대로 시스템을 구현할지

새로운 도메인 Rule을 결정해서 진행 할지 각자 의견이 필요할 것 같습니다.

**Comment by jjcec** [comment]
기존의 인턴에서 사용하던 Rule을 토대로 하는점은 괜찮을 것 같습니다.
기존 도메인을 사용하되 추가적으로 새로운 부분들도 추가하는 것이 좋을 것 같습니다. 
예를 들어 각자의 체질같은 사람들이 관심을 더 쉽게 갖을 수 있을만한 부분들이 필요할 것 같습니다.

**Comment by KimTaeWoo-CS** [comment]
기존의 Rule은 저희가 기술적으로 구현하기 힘든 부분도 포함하고 있기 때문에 먼저 저희가 어떤 범위까지 개발할지 정하고 분석/정리해 사용하는 것이 좋을 것 같습니다.

**Comment by junyeongRue** [comment]
새로운 도메인 분석시 전문가적인 지식을 찾기까지 상당히 오랜시간이 걸릴것으로 예상됩니다. 
기존 인턴으로 그나마 익숙하고 생각해보았던 룰을 사용하는 것이 적합할것 같습니다. 
(위에서 말한 기술적으로 구현이 힘든 부분 또한 고려하여야 할것으로 판단됩니다.)
