### ISSUE TITLE
캡스톤 계획서 작성 관련

### ISSUE THREAD

**Issue by zcx6263** [kookmin-sw/2018-cap1-4#2]
저번 회의에서 인턴에서 분석했던 Rule을 사용하되 추가적인 Rule 도메인을 적용하여 
기존에 존재하는 Medical Expert System 과 차별화가 되어야 한다는 의견이 나왔고
모두 동의하였습니다.
이를 바탕으로 캡스톤 계획서 작성에 대해 역할분담을 하여 조사하고 정리한 내용을 
보내주시면 됩니다.
장원용 - Expert System 구조, 기술적 요구사항, 개발 목표 확립
김태우 - use case, sequence diagram 수정 및 보완, 새로 적용 할 Rule 분석
류준영 - 사상체질 , 수지침에 대한 Rule 조사 (대한한의학협회 참고)
차은채 - 대중화 되어있는 IBM 닥터 왓슨 사례, 보건복지부 통계 자료 조사

조사한 내용을 보내주시고 
장원용, 류준영은 계획서 수정 및 보완
김태우, 차은채 발표 PPT 작성으로 역할 분담을 하겠습니다.

**Comment by junyeongRue** [comment]
확인했습니다~.
사상체질이 생각보다 뚜렷하게 구별되는 룰이 확정적이지 않은것 같습니다.
계속하여 자료 조사 중에 있습니다 확정적인 rule을 찾고 
아니면 ~(ex) 태양인, 태음인 등)에 가깝다는 진단을 내리는 방향으로 해야 할수도 있겠습니다.

**Comment by KimTaeWoo-CS** [comment]
확인했습니다.
Diagram의 경우에는 혼자서 작성하기 보다 개발방향을 토의하고 작성해야 할 것 같습니다.
새로 적용 할 Rule에 관해서는 Rule의 사용범위를 먼저 정하고 분석해야 할 것 같습니다.

**Comment by jjcec** [comment]
확인했습니다.
보건복지부의 통계적 수치에 따르면 국민들에게 있어서 한방의료를 이용한 경험자 수도 많고 그에 따른 만족감도 높은 것으로 나왔습니다. 
많은 국민들이 한방의료를 인식하고 있고 전체 국민의 84.2%라는 높은 수치로 향후 한방의료를 이용할 의향이 있는 것으로 파악되었습니다. 
국민들에게 있어서 현재 한방의료의 선호도가 높고 앞으로의 전망도 밝을 것이라고 생각합니다.
그래서 저희의 한방의료 진단 처방 시스템은 많은 국민들에게 있어서 큰 파급력을 가져올 것이라고 기대됩니다.
