### ISSUE TITLE
캡스톤 계획서 최종 검토

### ISSUE THREAD

**Issue by zcx6263** [kookmin-sw/2018-cap1-4#3]
2018.03.09 지도교수님과 회의 후 피드백 받은 내용을 수정하였고,
최종본을 올리기전 각자 최종 검토가 필요할 것 같습니다.
계획서의 문서 정보/ 수정 내역에 팀원들 이름을 올려두었으니
각자 최종검토 후 수정 내역을 적어주셔서 다시 보내주시면 됩니다.

**Comment by KimTaeWoo-CS** [comment]
확인했습니다.

**Comment by junyeongRue** [comment]
수정 완료 확인 했습니다.

**Comment by jjcec** [comment]
수정 완료 확인 완료.
