### ISSUE TITLE
3.15 회의 및 안건 (서버 로드밸런싱 구성)

### ISSUE THREAD

**Issue by zcx6263** [kookmin-sw/2018-cap1-4#4]
매주 회의를 목요일로 정했는데 시간이 가능한지 답글 남겨 줄 것 
또한 저번 교수님과 회의에서 웹에서 의사가 아닌 일반사람들도 웹을 접근 후 이용
가능하게 하려면 앞단에 아파치서버 를 추가해서 로드밸런싱을 구성하는 부분에 
대해서 검토가 필요 할 것 같습니다. 
또한, 아래 내용에 대해서 준비해서 회의를 가졌음 하고 에로 사항 등 답글 부탁드립니다.
장원용: 로드밸런싱 (아파치서버 단점 보완한 엔진엑스 검토)
김태우 : 수지침 Rule 추가 및 정리, 아파치 서버 검토
류준영 : 사상체질 Rule 추가 및 정리 (기존 Rule 진단과 연결)
차은채 : UI 구성 하기위한 개발 환경 구축

**Comment by junyeongRue** [comment]
사상체질 Rule 추가는 설문항목의 추가와 함께 새로운 DB table 구성이 필요합니다.
 먼저 사상체질 Rule 에 대한 검증부터 하고 나서 진행하겠습니다.

**Comment by jjcec** [comment]
목요일 시간 가능합니다. UI적인 부분에선 사용자들에게 편리하고 한눈에 알아보기 쉽게할 수 있는 전체적인 틀을 잡는 부분에 대해 의견듣고 싶습니다.
